apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cica-online-circleci-test
spec:
  selector:
    matchLabels:
      app: cica-online-circleci-test
  replicas: 2
  template:
    metadata:
      labels:
        app: cica-online-circleci-test
    spec:
      containers:
      - name: cica-online-circleci-test
        image: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/cica/cicadevelopment:cica-dev-test
        ports:
        - containerPort: 3000
#        livenessProbe:
#          httpGet:
#            path: /
#            port: 4010
#          initialDelaySeconds: 15
#          timeoutSeconds: 1
#          periodSeconds: 10


---
kind: Service
apiVersion: v1
metadata:
  name: cica-online-circleci-test-service
  labels:
    app: cica-online-staging-service
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 3000
  selector:
    app: cica-online-circleci-test


---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cica-online-circleci-test-ingress
spec:
  rules:
  - host: cica-online-dev.apps.cloud-platform-live-0.k8s.integration.dsd.io
    http:
      paths:
      - path: /
        backend:
          serviceName: cica-online-circleci-test-service
          servicePort: 8080
