
# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Image tool container
      - image: ${ECR_REPOSITORY}/${ECR_REPO_NAME}:image-tools-circleci
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
              docker build -t $IMAGE_CONTAINER .
      - run:
          name: Authenticate and push image to ecr
          command: |
              $(aws ecr get-login --region eu-west-1 --no-include-email)
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                 docker tag $IMAGE_CONTAINER:latest ${ECR_REPOSITORY}/${ECR_REPO_NAME}:cica-dev-test
                 docker push ${ECR_REPOSITORY}/${ECR_REPO_NAME}:cica-dev-test
              fi

  deploy_to_dev:
    docker:
      - image: ${ECR_REPOSITORY}/${ECR_REPO_NAME}:image-tools-circleci
    environment:
      AWS_DEFAULT_OUTPUT: json
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy to the cluster
          command: |
              $(aws ecr get-login --region eu-west-1 --no-include-email)
              setup-kube-auth
              kubectl config use-context development
              ./deploy_dev.sh



workflows:
  version: 2
  build-push-deploy:
    jobs:
      - build
      - deploy_to_dev:
          requires:
             - build
          filters:
            branches:
              only: master





#      - push:
#          requires:
#            - build
#          filters:
#            branches:
#              only: develop
#      - deploy:
#          requires:
#             - push
#          filters:
#             branches:
#                only: develop



#  test
